-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Complementa instalaciones existentes de Gregorisa.

ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS numero BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS metodo_pago TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS atendido_por TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS estado_pago TEXT NOT NULL DEFAULT 'pendiente'
  CHECK (estado_pago IN ('pendiente','pagado','rechazado','reembolsado'));
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS referencia_pago TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS culqi_charge_id TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS fecha_pago TIMESTAMPTZ;
ALTER TABLE pedido_items ADD COLUMN IF NOT EXISTS descuento_pct NUMERIC(5,2) NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS pedidos_culqi_charge_unique
  ON pedidos(culqi_charge_id) WHERE culqi_charge_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS pagos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id INTEGER NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
  proveedor TEXT NOT NULL DEFAULT 'culqi',
  estado TEXT NOT NULL CHECK (estado IN ('pendiente','pagado','rechazado','reembolsado')),
  metodo TEXT,
  monto NUMERIC(10,2) NOT NULL,
  moneda TEXT NOT NULL DEFAULT 'PEN',
  culqi_charge_id TEXT,
  referencia TEXT,
  ultimos_cuatro TEXT,
  mensaje TEXT,
  respuesta JSONB,
  pagado_por TEXT,
  pagado_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS pagos_culqi_charge_unique
  ON pagos(culqi_charge_id) WHERE culqi_charge_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS pagos_pedido_idx ON pagos(pedido_id);
CREATE INDEX IF NOT EXISTS pagos_created_at_idx ON pagos(created_at DESC);

ALTER TABLE pagos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pagos lectura auth" ON pagos;
CREATE POLICY "pagos lectura auth" ON pagos FOR SELECT USING (auth.role() = 'authenticated');

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE pagos;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
